name: Run

on:
  push

jobs:
  Run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    
    - name: Build benchmarks
      run: dotnet publish -c Release
    
    - name: Run benchmarks
      run: dotnet BenchmarkMockNet.dll
      working-directory: bin/Release/net5.0/publish
    
    - name: Upload results
      uses: actions/upload-artifact@v2
      with:
        name: Results
        path: bin/Release/net5.0/publish/BenchmarkDotNet.Artifacts/results/*.md
